language: php

php:
  - 5.4
  - 5.5
  - 5.6

install:
  - composer install --dev

script: php vendor/bin/phpunit --testsuite unit --coverage-clover ./tmp/clover.xml

after_script:
  - php vendor/bin/coveralls -v
